name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libconfig-dev python3 python3-pip

    - name: Set up Python dependencies
      run: |
        pip3 install bypy

    - name: Configure
      run: ./configure

    - name: Build
      run: make

    - name: Run tests
      run: make check

    - name: Run distribution check
      run: make distcheck

    - name: Static analysis with cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --inconclusive --std=c99 --language=c src/

    - name: Static analysis with clang-tidy
      run: |
        sudo apt-get install -y clang-tidy
        clang-tidy src/*.c -- -I/usr/include/libconfig

    - name: Cache compiled files
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          build
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-build-
